# Generated by Django 3.0.7 on 2020-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('recieved_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('sold_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('sold_by', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
