# Generated by Django 3.0.7 on 2020-06-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stock_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
    ]
