# Generated by Django 3.0.7 on 2020-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_stock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
