# Generated by Django 3.0.7 on 2020-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(default='5G.jpg', upload_to=''),
        ),
    ]
