# Generated by Django 3.0.7 on 2020-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200622_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
