# Generated by Django 3.0.7 on 2020-06-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_stock_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sold',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
