# Generated by Django 3.0.7 on 2020-06-23 15:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpemail',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtppassword',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpport',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpserver',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='twitter',
        ),
        migrations.AddField(
            model_name='stock',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
