# Generated by Django 3.0.7 on 2020-06-23 16:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200623_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='main',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
