# Generated by Django 3.0.7 on 2020-06-23 16:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_setting_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='features',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
