# Generated by Django 2.2.4 on 2020-06-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_setting_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=250, null=True)),
                ('business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('primary_business_address', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(default='', upload_to='images/clients')),
                ('number_of_staff', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
