# Generated by Django 2.2.4 on 2020-06-24 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
